traduction fr des paragraphes suivants : We actively work towards, We…
Android-Dev-FR/Code_de_conduite_Slack_Android_Dev_FR pull request #3
Opened 2020-06-20 18:09 UTC by lopspower

3 new sections in french:
- We actively work towards:
- We condemn:
- If you say something that is found offensive, and you are called out on it, let’s:

2020-06-20 18:28 UTC, FannyDemey commented on README.md
> +* Ecoutons sans interrompre
Ecoutes (et en général sur les 4 phrase mettre a la 2eme pers sing.

2020-06-21 21:42 UTC, LouisCAD requested changes
Très bien 👍 
J'ai tenté d'améliorer légèrement la lisibilité avec quelques suggestions, et en rebondissant sur celle de @FannyDemey d'utiliser la 2ème personne du singulier plutôt que la 1ère personne du pluriel.

2020-06-21 21:42 UTC, LouisCAD commented on README.md
> +* Développer un réseau de soutien et d'encouragement pour tous
```suggestion
* Cultiver un réseau de soutien et d'encouragement pour tous
```

2020-06-21 21:42 UTC, LouisCAD commented on README.md
> +* Encourager l'utilisation d'une forme d'expression variée et responsable
```suggestion
* Encourager des formes d'expression responsables et variées
```

2020-06-21 21:42 UTC, LouisCAD commented on README.md
> +* Ecoutons sans interrompre
```suggestion
* Ecoute sans interrompre.
```

2020-06-21 21:42 UTC, LouisCAD commented on README.md
> +* Faisons confiance en ce que la personne dit et n'essayons pas de discréditer ce qu'elle a à dire
```suggestion
* Crois ce que la personne dit et n'essaye pas de discréditer ce qu'elle a à dire.
```

2020-06-21 21:42 UTC, LouisCAD commented on README.md
> +* Demandons des conseils / de l'aide pour éviter de commettre une nouvelle infraction
```suggestion
* Demande des conseils / de l'aide pour éviter de commettre une nouvelle infraction.
```

2020-06-21 21:42 UTC, LouisCAD commented on README.md
> +* Présentons nos excuses et demandons pardon
```suggestion
* Présente tes excuses et demande le pardon.
```

2020-06-21 21:42 UTC, LouisCAD commented on README.md
> +Le non-respect des directives communautaires décrites dans ce document entraîne des conséquences. Pour des infractions mineures, vous pouvez être temporairement suspendu du Slack. En cas de récidive
```suggestion
Le non-respect des directives communautaires décrites dans ce document entraîne des conséquences. Pour des infractions mineures, vous pouvez être temporairement suspendu du Slack. En cas de récidive, ou si la communauté pense que vous n'agissez pas de bonne foi, il se peut que l'on vous demande de quitter définitivement ce Slack.
```

2020-06-21 21:42 UTC, LouisCAD commented on README.md
> +* Etre une communauté sûre
```suggestion
* Etre une communauté sûre et saine
```
Le mot "safe" en Anglais porte plus de sens que le mot "sûr" en français, donc je propose de rajouter le mot "sain(e)".

2020-06-21 21:42 UTC, LouisCAD commented on README.md
> +### Si tu dis quelque chose qui est jugé offensant, et qu'on te le fait remarquer, alors :
```suggestion
### Si tu dis quelque chose qui est trouvé offensant, et qu'on te le fait remarquer :
```
Le mot "jugé" étant plus fort, il couvre moins les micro-aggressions contrairement à "trouvé".

Pour le connecteur "alors", je trouve que ça se lit mieux sans.

2020-06-22 16:43 UTC, merged