proposition moderation admin
Android-Dev-FR/Code_de_conduite_Slack_Android_Dev_FR pull request #4
Opened 2020-06-21 18:52 UTC by FannyDemey

2020-06-21 19:01 UTC, LouisCAD requested changes
Bon ajout dans le code de conduite.

J'ai suggéré quelques corrections mineures, et quelques rajoutes/modifications  que je suis prêt à discuter ou reconsidérer.

2020-06-21 19:01 UTC, LouisCAD commented on README.md
> +Face à un comportement non adéquate d'une personne sur cet espace slack, l'équipe d'admins peut prendre toute action qui lui semble adéquate.
```suggestion
Face à un comportement non adéquat d'une personne sur cet espace Slack, l'équipe d'admins peut prendre toute action qui lui semble adéquate.
```

2020-06-21 19:01 UTC, LouisCAD commented on README.md
> +Cela va d'un simple avertissement à l'exclusion du groupe.
```suggestion
Cela va d'un simple avertissement à la désactivation du compte.
```

2020-06-21 19:01 UTC, LouisCAD commented on README.md
> +* Demander à une personne de reformuler ses propos en faisant preuve de communication non violente*.
L'étoile en fine de ligne fait référence à une note de bas de page manquante, ou c'est une mise en italique ou en gras incomplète ?

2020-06-21 19:01 UTC, LouisCAD commented on README.md
> +* Supprimer un ou plusieurs messages voir supprimer un thread complet
```suggestion
* Supprimer un ou plusieurs messages, voire supprimer un thread complet
```

2020-06-21 19:01 UTC, LouisCAD commented on README.md
> +Les admins peuvent agir suite au signalement d'un comportement inadéquate par un ou plusieurs membres du groupe, ou de leur propre chef.
```suggestion
Les admins peuvent agir suite au signalement d'un comportement inadéquat par un ou plusieurs membres du groupe, ou de leur propre chef.
```

2020-06-21 19:01 UTC, LouisCAD commented on README.md
> +#### Les régles de la communication non violente
```suggestion
#### Les règles de la communication non violente
```

2020-06-21 19:01 UTC, LouisCAD commented on README.md
> +2. Partager son ressenti en disant "Je"
```suggestion
2. Partager son ressenti en disant "Je" (pour marquer la subjectivité)
```

2020-06-21 19:04 UTC, florent37 commented on README.md
> +* Banir temporairement ou définitivement une personne
Je ne sais pas si on peut bannir temporairement, tu tiens ça d'un autre slack ? Si oui techniquement c'est peut être possible

2020-06-21 19:04 UTC, florent37 commented
Les phrases sont très bien tournées, j'ai ajouté une petite question, je vais voir demain techniquement ce qu'il est possible de faire concernant les suspensions de compte

2020-06-21 19:54 UTC, FannyDemey commented on README.md
> +* Demander à une personne de reformuler ses propos en faisant preuve de communication non violente*.
c'est pour faire référence.

2020-06-21 19:55 UTC, FannyDemey commented on README.md
> +* Banir temporairement ou définitivement une personne
nop j'en sais rien en fait tu peux check ?

2020-06-21 21:12 UTC, LouisCAD commented on README.md
> +* Banir temporairement ou définitivement une personne
@florent37 On peut "désactiver" un compte, donc on peut aussi le réactiver.

2020-06-21 21:19 UTC, LouisCAD approved these changes
Pour moi, la qualité et le contenu sont suffisamment bons pour que ça soit intégré.

2020-06-21 21:19 UTC, LouisCAD commented on README.md
> +#### Les règles de la communication non violente
```suggestion
#### \*Les règles de la communication non violente
```

C'est pour faire le lien avec l'astérisque plus haut, faudra vérifier le rendu markdown avec l'escaping si on est d'accord sur ce détail.

2020-06-22 05:37 UTC, florent37 commented on README.md
> +* Banir temporairement ou définitivement une personne
Ça marche

2020-06-22 06:58 UTC, florent37 approved these changes
Oui tout me semble bien expliqué, et correct, j'approuve

2020-06-22 06:58 UTC, merged